version: '3.9'
services:
  # app:
  #   container_name: golang_container
  #   tty: true
  #   build: .
  #   ports:
  #     - 8081:8080
  #   restart: on-failure
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - postgresdb
  #   networks:
  #     - deploy

  postgresdb:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookservice
    ports:
      - '5431:5432'
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    # networks:
    #   - deploy

volumes:
  pg_data:
# networks:
#   deploy:
#     driver: bridge
