database_config:
  host: 127.0.0.1
  user: postgres
  password: root
  dbname: bookservice
  port: 5431
  sslmode: disable

redis:
  host: localhost

http_server:
  port: 8081
  timeout: 10s
  idle_timeout: 60s
