

database_config:
  host: localhost
  user: postgres
  password: root
  dbname: bookservice
  port: 5432
  sslmode: disable

redis:
  host: localhost

http_server:
  port: 8081
  timeout: 10s
  idle_timeout: 60s
