database_config:
  host: 127.0.0.1
  user: postgres
  password: postgres
  dbname: bookservice
  port: 5432
  sslmode: disable

redis:
  host: localhost

http_server:
  port: 8080
  timeout: 10s
  idle_timeout: 60s
